# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pointofsaleitem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e271f2b9db8d48958794825db7571375 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1495713e2cc94fc691e119dac220dc5f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e271f2b9db8d48958794825db7571375 }}/point_of_sale_item:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pointofsaleitem'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d478982082f447adbf7f75f7eba7ef01 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e271f2b9db8d48958794825db7571375 }}/point_of_sale_item:${{ github.sha }}'